##Arithmetic Operations

In [1]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3] , "B":[4,5,6]})
print(var)

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
#var["C"] = var["A"] + var["B"]
#var["C"] = var["A"] - var["B"]
#var["C"] = var["A"] * var["B"]
#var["C"] = var["A"] / var["B"]

#var["C"] = var["A"][2] + var["B"][2]
#var_ans = var['C'][2]
# var_ans

np.int64(9)

In [17]:
var_1 = pd.DataFrame({"A": [12,24,39] , "B":[40,50,61]})
var_1["C"] = var_1["A"] + var_1["B"]
var_1

    A   B    C
0  12  40   52
1  24  50   74
2  39  61  100

In [19]:
var_1["Py"] = var_1["A"] <= 20
var_1["Py"] = var_1["B"] >= 41
var_1

    A   B    C     Py
0  12  40   52  False
1  24  50   74   True
2  39  61  100   True