#group by

In [25]:
import pandas as pd

var = pd.DataFrame({"Name": ["a","b","c","a","a","d","e","b","c","a","e","d"] , 
                    "S_1": [1, 2, 3, 1, 1, 5, 3, 3, 1, 4, 3, 2] , 
                    "S_2": [6, 8, 7, 8, 5, 5, 9, 7, 10,10, 7, 6]})

var

   Name  S_1  S_2
0     a    1    6
1     b    2    8
2     c    3    7
3     a    1    8
4     a    1    5
5     d    5    5
6     e    3    9
7     b    3    7
8     c    1   10
9     a    4   10
10    e    3    7
11    d    2    6

In [26]:
var_new = var.groupby("Name")
var_new

In [27]:
for x,y in var_new:
    print(x)
    print(y)
    print()

a
  Name  S_1  S_2
0    a    1    6
3    a    1    8
4    a    1    5
9    a    4   10

b
  Name  S_1  S_2
1    b    2    8
7    b    3    7

c
  Name  S_1  S_2
2    c    3    7
8    c    1   10

d
   Name  S_1  S_2
5     d    5    5
11    d    2    6

e
   Name  S_1  S_2
6     e    3    9
10    e    3    7

In [30]:
var_new.get_group("c")

  Name  S_1  S_2
2    c    3    7
8    c    1   10

In [32]:
var_new.min()

      S_1  S_2
Name
a       1    5
b       2    7
c       1    7
d       2    5
e       3    7

In [34]:
var_new.max()

      S_1  S_2
Name
a       4   10
b       3    8
c       3   10
d       5    6
e       3    9

In [40]:
var_new.mean()

       S_1   S_2
Name
a     1.75  7.25
b     2.50  7.50
c     2.00  8.50
d     3.50  5.50
e     3.00  8.00

In [ ]:
#converting in list
li = list(var_new)
li

[('a',
    Name  S_1  S_2
  0    a    1    6
  3    a    1    8
  4    a    1    5
  9    a    4   10),
 ('b',
    Name  S_1  S_2
  1    b    2    8
  7    b    3    7),
 ('c',
    Name  S_1  S_2
  2    c    3    7
  8    c    1   10),
 ('d',
     Name  S_1  S_2
  5     d    5    5
  11    d    2    6),
 ('e',
     Name  S_1  S_2
  6     e    3    9
  10    e    3    7)]