##insert

In [2]:
import pandas as pd

var = pd.DataFrame({"A": [1,2,3,4,5] , "B":[6,7,8,9,10]})
var

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [10]:
var.insert(1,"python_2" , var["A"])
var

   A  python_2  python_1  python   B
0  1         1         1       1   6
1  2         2         2       2   7
2  3         3         3       3   8
3  4         4         4       4   9
4  5         5         5       5  10

In [15]:
var.insert(1, "python_5" , [11,12,13,14,15])
var

   A  python_5  python_4  python_3  python_2  python_1  python   B
0  1        11        11        11         1         1       1   6
1  2        12        12        12         2         2       2   7
2  3        13        13        13         3         3       3   8
3  4        14        14       141         4         4       4   9
4  5        15        15        15         5         5       5  10

In [16]:
var["py"] = var["A"][:3]
var

   A  python_5  python_4  python_3  python_2  python_1  python   B   py
0  1        11        11        11         1         1       1   6  1.0
1  2        12        12        12         2         2       2   7  2.0
2  3        13        13        13         3         3       3   8  3.0
3  4        14        14       141         4         4       4   9  NaN
4  5        15        15        15         5         5       5  10  NaN

##Delete

In [25]:
var_5 = var.pop("python")
var_5
var

print(var_5)

KeyError: 'python'

In [29]:
print(var.columns)
print(var_5)
print(type(var_5))
print(var)

Index(['A', 'python_2', 'python_1', 'B', 'py'], dtype='object')
0    1
1    2
2    3
3    4
4    5
Name: python, dtype: int64
<class 'pandas.core.series.Series'>
   A  python_2  python_1   B   py
0  1         1         1   6  1.0
1  2         2         2   7  2.0
2  3         3         3   8  3.0
3  4         4         4   9  NaN
4  5         5         5  10  NaN