#melt

In [ ]:
import pandas as pd

var = pd.DataFrame({"days":[1,2,3,4,5,6] , 
                    "eng":[10, 20, 30, 40, 50, 60] , 
                    "maths":[17, 18, 19, 20, 21, 22]
                })

var

   days  eng  maths
0     1   10     17
1     2   20     18
2     3   30     19
3     4   40     20
4     5   50     21
5     6   60     22

In [42]:
melted = pd.melt(var , id_vars=["days"], var_name="subjects", value_name="scores")
#melted
result = melted.pivot(index = "days", columns="subjects", values="scores").reset_index()

result.columns.name = None

result

   days  eng  maths
0     1   10     17
1     2   20     18
2     3   30     19
3     4   40     20
4     5   50     21
5     6   60     22

#pivot

In [56]:
import pandas as pd

var = pd.DataFrame({"days":[1,2,3,4,5,6] ,
                    "st_name": ["a","a","b","b","a","b"] ,
                    "eng":[10, 20, 30, 40, 50, 60] , 
                    "maths":[17, 18, 19, 20, 21, 22]
                })

result = var.pivot(index = "days" , columns="st_name", values=["eng" , "maths"])
final = result.fillna("000000")
final

            eng           maths
st_name       a       b       a       b
days
1          10.0  000000    17.0  000000
2          20.0  000000    18.0  000000
3        000000    30.0  000000    19.0
4        000000    40.0  000000    20.0
5          50.0  000000    21.0  000000
6        000000    60.0  000000    22.0

In [64]:
var = pd.DataFrame({"days":[1,1,1,2,2,2] ,
                    "st_name": ["a","a","b","b","a","b"] ,
                    "eng":[10, 20, 30, 40, 50, 60] , 
                    "maths":[17, 18, 19, 20, 21, 22]
                })

result = var.pivot_table(index = "st_name" , columns="days", aggfunc="mean" , margins = True)
#final = result.fillna(0.0)
# final
result

          eng                  maths
days        1     2        All     1     2        All
st_name
a        15.0  50.0  26.666667  17.5  21.0  18.666667
b        30.0  50.0  43.333333  19.0  21.0  20.333333
All      20.0  50.0  35.000000  18.0  21.0  19.500000