#merge and concat

In [57]:
import pandas as pd

In [58]:
var1 = pd.DataFrame({"A":[1,2,3,4] , "B":[5,6,7,8]})
var2 = pd.DataFrame({"A":[1,2,3,5] , "B":[9,10,11,12]})
#result = pd.merge(var1 , var2)
#result = pd.merge(var1 , var2 , on="A")
#result = pd.merge(var1 , var2 , how="outer" , indicator = True)
#result = pd.merge(var1 , var2 , left_index= True , right_index= True)
#result = pd.merge(var1 , var2 , left_index= True , right_index= True)
result = pd.merge(var1 , var2 , left_index= True , right_index= True , suffixes=("name","java"))
result

   Aname  Bname  Ajava  Bjava
0      1      5      1      9
1      2      6      2     10
2      3      7      3     11
3      4      8      5     12

#concat

In [59]:
#concating two series
sr1 = pd.Series({"A": [1,2,3,4]})
sr2 = pd.Series({"B": [11,12,13,14]})
pd.concat([sr1 , sr2],axis = 0)

A        [1, 2, 3, 4]
B    [11, 12, 13, 14]
dtype: object

In [60]:
#concating two dataframes
d1 = pd.DataFrame({"A":[1,2,3,4] , "B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[5,6,7,8] , "C":[55,56,57,58]})
pd.concat([d1 , d2] ,axis = 0)

   A     B     C
0  1  11.0   NaN
1  2  12.0   NaN
2  3  13.0   NaN
3  4  14.0   NaN
0  5   NaN  55.0
1  6   NaN  56.0
2  7   NaN  57.0
3  8   NaN  58.0

In [61]:
#concating two dataframes
d1 = pd.DataFrame({"A":[1,2,3,4] , "B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[5,6,7,8] , "C":[55,56,57,58]})
#pd.concat([d1 , d2] ,axis = 1, join="outer")
pd.concat([d1 , d2] ,axis = 0, keys=["d1","d2"])

      A     B     C
d1 0  1  11.0   NaN
   1  2  12.0   NaN
   2  3  13.0   NaN
   3  4  14.0   NaN
d2 0  5   NaN  55.0
   1  6   NaN  56.0
   2  7   NaN  57.0
   3  8   NaN  58.0

In [65]:
#concating two dataframes
d1 = pd.DataFrame({"D":[1,2,3,4]})
d2 = pd.DataFrame({"A":[5,6,7,8] , "C":[55,56,57,58]})
pd.concat([d1,d2] , axis = 1 , keys=["d1" , "d2"])

  d1 d2
   D  A   C
0  1  5  55
1  2  6  56
2  3  7  57
3  4  8  58