##Pandas Functions

In [2]:
import pandas as pd

csv_1 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv", nrows = 25 )

csv_1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086,17.0,120.0,1.0,Urban,Y
15,LP001032,Male,No,0,Graduate,No,4950,0,125.0,360.0,1.0,Urban,Y
16,LP001034,Male,No,1,Not Graduate,No,3596,0,100.0,240.0,NaN,Urban,Y
17,LP001036,Female,No,0,Graduate,No,3510,0,76.0,360.0,0.0,Urban,N
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500,115.0,NaN,1.0,Urban,Y
20,LP001043,Male,Yes,0,Not Graduate,No,7660,0,104.0,360.0,0.0,Urban,N
21,LP001046,Male,Yes,1,Graduate,No,5955,5625,315.0,360.0,1.0,Urban,Y
22,LP001047,Male,Yes,0,Not Graduate,No,2600,1911,116.0,360.0,0.0,Semiurban,N
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925,151.0,360.0,NaN,Semiurban,N

In [11]:
csv_1.index

RangeIndex(start=0, stop=25, step=1)

In [12]:
csv_1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [15]:
csv_1.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,25.000000,25.000000,24.000000,24.000000,23.000000
mean,4176.520000,2201.040000,139.541667,345.000000,0.782609
std,2356.151967,2693.519081,76.391998,53.811264,0.421741
min,1299.000000,0.000000,17.000000,120.000000,0.000000
25%,2600.000000,0.000000,103.000000,360.000000,1.000000
50%,3510.000000,1526.000000,118.000000,360.000000,1.000000
75%,4950.000000,2840.000000,152.750000,360.000000,1.000000
max,12841.000000,10968.000000,349.000000,360.000000,1.000000

In [21]:
csv_1.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y

In [23]:
csv_1.tail(2)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
23,LP001050,NaN,Yes,2,Not Graduate,No,3365,1917,112.0,360.0,0.0,Rural,N
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925,151.0,360.0,NaN,Semiurban,N

In [29]:
csv_1[5:10]

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968,349.0,360.0,1.0,Semiurban,N

In [31]:
print(type(csv_1))

<class 'pandas.core.frame.DataFrame'>

In [43]:
print(csv_1.index.to_series())
print(csv_1.index.to_frame())
print(csv_1.index.array)
print(csv_1.index.to_list())
print(csv_1.index.name)

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
dtype: int64
     0
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10
11  11
12  12
13  13
14  14
15  15
16  16
17  17
18  18
19  19
20  20
21  21
22  22
23  23
24  24
<NumpyExtensionArray>
[ np.int64(0),  np.int64(1),  np.int64(2),  np.int64(3),  np.int64(4),
  np.int64(5),  np.int64(6),  np.int64(7),  np.int64(8),  np.int64(9),
 np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14),
 np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19),
 np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24)]
Length: 25, dtype: int64
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
None

In [44]:
csv_1.to_numpy()

array([['LP001002', 'Male', 'No', '0', 'Graduate', 'No', 5849, 0, nan,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001003', 'Male', 'Yes', '1', 'Graduate', 'No', 4583, 1508,
        128.0, 360.0, 1.0, 'Rural', 'N'],
       ['LP001005', 'Male', 'Yes', '0', 'Graduate', 'Yes', 3000, 0, 66.0,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001006', 'Male', 'Yes', '0', 'Not Graduate', 'No', 2583, 2358,
        120.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001008', 'Male', 'No', '0', 'Graduate', 'No', 6000, 0, 141.0,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001011', 'Male', 'Yes', '2', 'Graduate', 'Yes', 5417, 4196,
        267.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001013', 'Male', 'Yes', '0', 'Not Graduate', 'No', 2333, 1516,
        95.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001014', 'Male', 'Yes', '3+', 'Graduate', 'No', 3036, 2504,
        158.0, 360.0, 0.0, 'Semiurban', 'N'],
       ['LP001018', 'Male', 'Yes', '2', 'Graduate', 'No', 4006, 1526,
        168.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001020', 'Male', 'Yes', '1', 'Graduate', 'No', 12841, 10968,
        349.0, 360.0, 1.0, 'Semiurban', 'N'],
       ['LP001024', 'Male', 'Yes', '2', 'Graduate', 'No', 3200, 700,
        70.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001027', 'Male', 'Yes', '2', 'Graduate', nan, 2500, 1840,
        109.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001028', 'Male', 'Yes', '2', 'Graduate', 'No', 3073, 8106,
        200.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001029', 'Male', 'No', '0', 'Graduate', 'No', 1853, 2840,
        114.0, 360.0, 1.0, 'Rural', 'N'],
       ['LP001030', 'Male', 'Yes', '2', 'Graduate', 'No', 1299, 1086,
        17.0, 120.0, 1.0, 'Urban', 'Y'],
       ['LP001032', 'Male', 'No', '0', 'Graduate', 'No', 4950, 0, 125.0,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001034', 'Male', 'No', '1', 'Not Graduate', 'No', 3596, 0,
        100.0, 240.0, nan, 'Urban', 'Y'],
       ['LP001036', 'Female', 'No', '0', 'Graduate', 'No', 3510, 0, 76.0,
        360.0, 0.0, 'Urban', 'N'],
       ['LP001038', 'Male', 'Yes', '0', 'Not Graduate', 'No', 4887, 0,
        133.0, 360.0, 1.0, 'Rural', 'N'],
       ['LP001041', 'Male', 'Yes', '0', 'Graduate', nan, 2600, 3500,
        115.0, nan, 1.0, 'Urban', 'Y'],
       ['LP001043', 'Male', 'Yes', '0', 'Not Graduate', 'No', 7660, 0,
        104.0, 360.0, 0.0, 'Urban', 'N'],
       ['LP001046', 'Male', 'Yes', '1', 'Graduate', 'No', 5955, 5625,
        315.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001047', 'Male', 'Yes', '0', 'Not Graduate', 'No', 2600, 1911,
        116.0, 360.0, 0.0, 'Semiurban', 'N'],
       ['LP001050', nan, 'Yes', '2', 'Not Graduate', 'No', 3365, 1917,
        112.0, 360.0, 0.0, 'Rural', 'N'],
       ['LP001052', 'Male', 'Yes', '1', 'Graduate', nan, 3717, 2925,
        151.0, 360.0, nan, 'Semiurban', 'N']], dtype=object)

In [46]:
import numpy as np

v = np.asarray(csv_1)
v

array([['LP001002', 'Male', 'No', '0', 'Graduate', 'No', 5849, 0, nan,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001003', 'Male', 'Yes', '1', 'Graduate', 'No', 4583, 1508,
        128.0, 360.0, 1.0, 'Rural', 'N'],
       ['LP001005', 'Male', 'Yes', '0', 'Graduate', 'Yes', 3000, 0, 66.0,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001006', 'Male', 'Yes', '0', 'Not Graduate', 'No', 2583, 2358,
        120.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001008', 'Male', 'No', '0', 'Graduate', 'No', 6000, 0, 141.0,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001011', 'Male', 'Yes', '2', 'Graduate', 'Yes', 5417, 4196,
        267.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001013', 'Male', 'Yes', '0', 'Not Graduate', 'No', 2333, 1516,
        95.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001014', 'Male', 'Yes', '3+', 'Graduate', 'No', 3036, 2504,
        158.0, 360.0, 0.0, 'Semiurban', 'N'],
       ['LP001018', 'Male', 'Yes', '2', 'Graduate', 'No', 4006, 1526,
        168.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001020', 'Male', 'Yes', '1', 'Graduate', 'No', 12841, 10968,
        349.0, 360.0, 1.0, 'Semiurban', 'N'],
       ['LP001024', 'Male', 'Yes', '2', 'Graduate', 'No', 3200, 700,
        70.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001027', 'Male', 'Yes', '2', 'Graduate', nan, 2500, 1840,
        109.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001028', 'Male', 'Yes', '2', 'Graduate', 'No', 3073, 8106,
        200.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001029', 'Male', 'No', '0', 'Graduate', 'No', 1853, 2840,
        114.0, 360.0, 1.0, 'Rural', 'N'],
       ['LP001030', 'Male', 'Yes', '2', 'Graduate', 'No', 1299, 1086,
        17.0, 120.0, 1.0, 'Urban', 'Y'],
       ['LP001032', 'Male', 'No', '0', 'Graduate', 'No', 4950, 0, 125.0,
        360.0, 1.0, 'Urban', 'Y'],
       ['LP001034', 'Male', 'No', '1', 'Not Graduate', 'No', 3596, 0,
        100.0, 240.0, nan, 'Urban', 'Y'],
       ['LP001036', 'Female', 'No', '0', 'Graduate', 'No', 3510, 0, 76.0,
        360.0, 0.0, 'Urban', 'N'],
       ['LP001038', 'Male', 'Yes', '0', 'Not Graduate', 'No', 4887, 0,
        133.0, 360.0, 1.0, 'Rural', 'N'],
       ['LP001041', 'Male', 'Yes', '0', 'Graduate', nan, 2600, 3500,
        115.0, nan, 1.0, 'Urban', 'Y'],
       ['LP001043', 'Male', 'Yes', '0', 'Not Graduate', 'No', 7660, 0,
        104.0, 360.0, 0.0, 'Urban', 'N'],
       ['LP001046', 'Male', 'Yes', '1', 'Graduate', 'No', 5955, 5625,
        315.0, 360.0, 1.0, 'Urban', 'Y'],
       ['LP001047', 'Male', 'Yes', '0', 'Not Graduate', 'No', 2600, 1911,
        116.0, 360.0, 0.0, 'Semiurban', 'N'],
       ['LP001050', nan, 'Yes', '2', 'Not Graduate', 'No', 3365, 1917,
        112.0, 360.0, 0.0, 'Rural', 'N'],
       ['LP001052', 'Male', 'Yes', '1', 'Graduate', nan, 3717, 2925,
        151.0, 360.0, nan, 'Semiurban', 'N']], dtype=object)

In [81]:
#csv_1.sort_index(axis = 0 , ascending = True)
#csv_1.columns

In [92]:
#csv_1.sort_index(ascending = True).head(4)
csv_1_sorted = csv_1.sort_index(axis = 0 , ascending =True)
csv_2 = csv_1_sorted.head(4)
csv_2

,ApplicantIncome,CoapplicantIncome,Credit_History,Dependents,Education,Gender,LoanAmount,Loan_Amount_Term,Loan_ID,Loan_Status,Married,Property_Area,Self_Employed
0,1000,0,1.0,0,Graduate,Male,NaN,360.0,LP001002,Y,No,Urban,No
1,4583,1508,1.0,1,Graduate,Male,128.0,360.0,LP001003,N,Yes,Rural,No
2,3000,0,1.0,0,Graduate,Male,66.0,360.0,LP001005,Y,Yes,Urban,Yes
3,2583,2358,1.0,0,Not Graduate,Male,120.0,360.0,LP001006,Y,Yes,Urban,No

In [93]:
csv_2["ApplicantIncome"][0] = 10
csv_2

C:\Users\asus\AppData\Local\Temp\ipykernel_1972\3743951620.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  csv_2["ApplicantIncome"][0] = 10
C:\Users\asus\AppData\Local\Temp\ipykernel_1972\3743951620.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_2["ApplicantIncome"][0] = 10

,ApplicantIncome,CoapplicantIncome,Credit_History,Dependents,Education,Gender,LoanAmount,Loan_Amount_Term,Loan_ID,Loan_Status,Married,Property_Area,Self_Employed
0,10,0,1.0,0,Graduate,Male,NaN,360.0,LP001002,Y,No,Urban,No
1,4583,1508,1.0,1,Graduate,Male,128.0,360.0,LP001003,N,Yes,Rural,No
2,3000,0,1.0,0,Graduate,Male,66.0,360.0,LP001005,Y,Yes,Urban,Yes
3,2583,2358,1.0,0,Not Graduate,Male,120.0,360.0,LP001006,Y,Yes,Urban,No

In [98]:
csv_2.loc[0 , "ApplicantIncome"] = 100
csv_2.sort_index(axis = 0 , ascending = True)
csv_2

,ApplicantIncome,CoapplicantIncome,Credit_History,Dependents,Education,Gender,LoanAmount,Loan_Amount_Term,Loan_ID,Loan_Status,Married,Property_Area,Self_Employed
0,100,0,1.0,0,Graduate,Male,NaN,360.0,LP001002,Y,No,Urban,No
1,4583,1508,1.0,1,Graduate,Male,128.0,360.0,LP001003,N,Yes,Rural,No
2,3000,0,1.0,0,Graduate,Male,66.0,360.0,LP001005,Y,Yes,Urban,Yes
3,2583,2358,1.0,0,Not Graduate,Male,120.0,360.0,LP001006,Y,Yes,Urban,No

,ApplicantIncome,CoapplicantIncome,Credit_History,Dependents,Education,Gender,LoanAmount,Loan_Amount_Term,Loan_ID,Loan_Status,Married,Property_Area,Self_Employed
24,3717,2925,NaN,1,Graduate,Male,151.0,360.0,LP001052,N,Yes,Semiurban,NaN
23,3365,1917,0.0,2,Not Graduate,NaN,112.0,360.0,LP001050,N,Yes,Rural,No
22,2600,1911,0.0,0,Not Graduate,Male,116.0,360.0,LP001047,N,Yes,Semiurban,No
21,5955,5625,1.0,1,Graduate,Male,315.0,360.0,LP001046,Y,Yes,Urban,No
20,7660,0,0.0,0,Not Graduate,Male,104.0,360.0,LP001043,N,Yes,Urban,No
19,2600,3500,1.0,0,Graduate,Male,115.0,NaN,LP001041,Y,Yes,Urban,NaN
18,4887,0,1.0,0,Not Graduate,Male,133.0,360.0,LP001038,N,Yes,Rural,No
17,3510,0,0.0,0,Graduate,Female,76.0,360.0,LP001036,N,No,Urban,No
16,3596,0,NaN,1,Not Graduate,Male,100.0,240.0,LP001034,Y,No,Urban,No
15,4950,0,1.0,0,Graduate,Male,125.0,360.0,LP001032,Y,No,Urban,No
14,1299,1086,1.0,2,Graduate,Male,17.0,120.0,LP001030,Y,Yes,Urban,No
13,1853,2840,1.0,0,Graduate,Male,114.0,360.0,LP001029,N,No,Rural,No
12,3073,8106,1.0,2,Graduate,Male,200.0,360.0,LP001028,Y,Yes,Urban,No
11,2500,1840,1.0,2,Graduate,Male,109.0,360.0,LP001027,Y,Yes,Urban,NaN
10,3200,700,1.0,2,Graduate,Male,70.0,360.0,LP001024,Y,Yes,Urban,No
9,12841,10968,1.0,1,Graduate,Male,349.0,360.0,LP001020,N,Yes,Semiurban,No
8,4006,1526,1.0,2,Graduate,Male,168.0,360.0,LP001018,Y,Yes,Urban,No
7,3036,2504,0.0,3+,Graduate,Male,158.0,360.0,LP001014,N,Yes,Semiurban,No
6,2333,1516,1.0,0,Not Graduate,Male,95.0,360.0,LP001013,Y,Yes,Urban,No
5,5417,4196,1.0,2,Graduate,Male,267.0,360.0,LP001011,Y,Yes,Urban,Yes
4,6000,0,1.0,0,Graduate,Male,141.0,360.0,LP001008,Y,No,Urban,No
3,2583,2358,1.0,0,Not Graduate,Male,120.0,360.0,LP001006,Y,Yes,Urban,No
2,3000,0,1.0,0,Graduate,Male,66.0,360.0,LP001005,Y,Yes,Urban,Yes
1,4583,1508,1.0,1,Graduate,Male,128.0,360.0,LP001003,N,Yes,Rural,No
0,100,0,1.0,0,Graduate,Male,NaN,360.0,LP001002,Y,No,Urban,No

In [105]:
csv_1 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv", nrows = 5 )
csv_1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360,1,Urban,Y

In [115]:
#result = csv_1.loc[[2,3] , ["Education","Self_Employed","ApplicantIncome","CoapplicantIncome"]]
#result = csv_1.loc[: , ["Education","Self_Employed","ApplicantIncome","CoapplicantIncome"]]
result = csv_1.loc[[2,3] , :]
result

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360,1,Urban,Y

In [117]:
csv_1 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv", nrows = 5 )

csv_1

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0,NaN,360,1,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508,128.0,360,1,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360,1,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360,1,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360,1,Urban,Y

In [3]:
location = csv_1.iloc[0,6]
print(location)

5849

In [19]:
#csv_1 = csv_1.drop(1, axis = 0)
csv_1_reset = csv_1.reset_index(drop = True )
csv_1.head(4)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267.0,360.0,1.0,Urban,Y

In [20]:
csv_1.head(4)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267.0,360.0,1.0,Urban,Y