##Read csv

In [2]:
import pandas as pd

csv_1 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv")

csv_1

,Event ID,Timestamp,Source IP,Destination IP,User Agent,Attack Type,Attack Severity,Data Exfiltrated,Threat Intelligence,Response Action
0,2019969e-ecfa-41c4-b681-9b684bc3b3bf,2020-02-07 23:46:57,219.80.193.15,44.155.75.24,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv...,Ransomware,Critical,False,Crime low this behind option tax product.,Eradicated
1,1668e954-781f-4731-94dc-24218b983ba1,2021-05-25 19:03:44,110.155.68.245,178.123.150.38,Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KH...,Malware,Critical,True,Responsibility work way effect.,Eradicated
2,0ef24a20-1d25-41fa-81b8-e19fb63e9e4c,2022-01-04 09:08:07,171.153.115.83,76.187.142.133,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,Ransomware,High,False,Artist though type imagine food push.,Eradicated
3,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,DDoS,Critical,False,In still military despite TV look.,Contained
4,783fd153-6b88-44c1-8db5-d882300088cc,2021-11-24 02:04:33,120.43.64.52,113.82.34.164,Mozilla/5.0 (iPad; CPU iPad OS 9_3_6 like Mac ...,Malware,Medium,False,Push always least police it range either.,Eradicated
...,...,...,...,...,...,...,...,...,...,...
19995,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Ransomware,Critical,False,Forward something wife.,Recovered
19996,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Ransomware,Low,True,Fund method election possible.,Eradicated
19997,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Ransomware,Medium,False,Network minute act reflect.,Contained
19998,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Malware,Critical,False,Amount sit ten.,Contained
19999,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,Malware,High,True,Most structure several.,Contained

In [ ]:
#csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" , nrows = 5)
#csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" , nrows = 5 , usecols = ["Event ID" , "Attack Type"])
#csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" , nrows = 5 , usecols = [ 0 , 6])
csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" ,)

print(type(csv_2))

csv_2

<class 'pandas.core.frame.DataFrame'>

,Event ID,Timestamp,Source IP,Destination IP,User Agent,Attack Type,Attack Severity,Data Exfiltrated,Threat Intelligence,Response Action
0,2019969e-ecfa-41c4-b681-9b684bc3b3bf,2020-02-07 23:46:57,219.80.193.15,44.155.75.24,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv...,Ransomware,Critical,False,Crime low this behind option tax product.,Eradicated
1,1668e954-781f-4731-94dc-24218b983ba1,2021-05-25 19:03:44,110.155.68.245,178.123.150.38,Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KH...,Malware,Critical,True,Responsibility work way effect.,Eradicated
2,0ef24a20-1d25-41fa-81b8-e19fb63e9e4c,2022-01-04 09:08:07,171.153.115.83,76.187.142.133,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,Ransomware,High,False,Artist though type imagine food push.,Eradicated
3,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,DDoS,Critical,False,In still military despite TV look.,Contained
4,783fd153-6b88-44c1-8db5-d882300088cc,2021-11-24 02:04:33,120.43.64.52,113.82.34.164,Mozilla/5.0 (iPad; CPU iPad OS 9_3_6 like Mac ...,Malware,Medium,False,Push always least police it range either.,Eradicated
...,...,...,...,...,...,...,...,...,...,...
19995,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Ransomware,Critical,False,Forward something wife.,Recovered
19996,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Ransomware,Low,True,Fund method election possible.,Eradicated
19997,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Ransomware,Medium,False,Network minute act reflect.,Contained
19998,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Malware,Critical,False,Amount sit ten.,Contained
19999,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,Malware,High,True,Most structure several.,Contained

In [ ]:
csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv")
#csv_3 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv"  , skiprows = [0 , 3])

#csv_3

,2019969e-ecfa-41c4-b681-9b684bc3b3bf,2020-02-07 23:46:57,219.80.193.15,44.155.75.24,"Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv:4.0; lg-UG) AppleWebKit/531.26.1 (KHTML, like Gecko) Version/4.1 Safari/531.26.1",Ransomware,Critical,False,Crime low this behind option tax product.,Eradicated
0,1668e954-781f-4731-94dc-24218b983ba1,2021-05-25 19:03:44,110.155.68.245,178.123.150.38,Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KH...,Malware,Critical,True,Responsibility work way effect.,Eradicated
1,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,DDoS,Critical,False,In still military despite TV look.,Contained
2,783fd153-6b88-44c1-8db5-d882300088cc,2021-11-24 02:04:33,120.43.64.52,113.82.34.164,Mozilla/5.0 (iPad; CPU iPad OS 9_3_6 like Mac ...,Malware,Medium,False,Push always least police it range either.,Eradicated
3,e3f69b23-e5d0-4a39-b894-ab87413a93b6,2022-06-11 02:11:58,114.170.234.8,36.246.60.2,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Insider Threat,Medium,False,Enough trip successful total every.,Recovered
4,8b292334-60f6-4693-b563-39f399a4fae9,2020-08-24 18:30:46,212.62.126.191,31.113.210.1,Mozilla/5.0 (Windows CE; yi-US; rv:1.9.2.20) G...,DDoS,Medium,False,Form nothing new agree.,Recovered
...,...,...,...,...,...,...,...,...,...,...
19993,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Ransomware,Critical,False,Forward something wife.,Recovered
19994,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Ransomware,Low,True,Fund method election possible.,Eradicated
19995,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Ransomware,Medium,False,Network minute act reflect.,Contained
19996,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Malware,Critical,False,Amount sit ten.,Contained
19997,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,Malware,High,True,Most structure several.,Contained

In [21]:
csv_4 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" , index_col = "Attack Type")
csv_4

,Event ID,Timestamp,Source IP,Destination IP,User Agent,Attack Severity,Data Exfiltrated,Threat Intelligence,Response Action
Attack Type,,,,,,,,,
Ransomware,2019969e-ecfa-41c4-b681-9b684bc3b3bf,2020-02-07 23:46:57,219.80.193.15,44.155.75.24,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv...,Critical,False,Crime low this behind option tax product.,Eradicated
Malware,1668e954-781f-4731-94dc-24218b983ba1,2021-05-25 19:03:44,110.155.68.245,178.123.150.38,Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KH...,Critical,True,Responsibility work way effect.,Eradicated
Ransomware,0ef24a20-1d25-41fa-81b8-e19fb63e9e4c,2022-01-04 09:08:07,171.153.115.83,76.187.142.133,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,High,False,Artist though type imagine food push.,Eradicated
DDoS,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,Critical,False,In still military despite TV look.,Contained
Malware,783fd153-6b88-44c1-8db5-d882300088cc,2021-11-24 02:04:33,120.43.64.52,113.82.34.164,Mozilla/5.0 (iPad; CPU iPad OS 9_3_6 like Mac ...,Medium,False,Push always least police it range either.,Eradicated
...,...,...,...,...,...,...,...,...,...
Ransomware,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Critical,False,Forward something wife.,Recovered
Ransomware,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Low,True,Fund method election possible.,Eradicated
Ransomware,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Medium,False,Network minute act reflect.,Contained
Malware,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Critical,False,Amount sit ten.,Contained
Malware,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,High,True,Most structure several.,Contained

In [ ]:
csv_5 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" , header = 0)
csv_5

,0ef24a20-1d25-41fa-81b8-e19fb63e9e4c,2022-01-04 09:08:07,171.153.115.83,76.187.142.133,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) Gecko/2010-08-27 15:07:09 Firefox/3.6.12,Ransomware,High,False,Artist though type imagine food push.,Eradicated
0,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,DDoS,Critical,False,In still military despite TV look.,Contained
1,783fd153-6b88-44c1-8db5-d882300088cc,2021-11-24 02:04:33,120.43.64.52,113.82.34.164,Mozilla/5.0 (iPad; CPU iPad OS 9_3_6 like Mac ...,Malware,Medium,False,Push always least police it range either.,Eradicated
2,e3f69b23-e5d0-4a39-b894-ab87413a93b6,2022-06-11 02:11:58,114.170.234.8,36.246.60.2,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Insider Threat,Medium,False,Enough trip successful total every.,Recovered
3,8b292334-60f6-4693-b563-39f399a4fae9,2020-08-24 18:30:46,212.62.126.191,31.113.210.1,Mozilla/5.0 (Windows CE; yi-US; rv:1.9.2.20) G...,DDoS,Medium,False,Form nothing new agree.,Recovered
4,36c0362b-2821-4e2b-bc6d-58bc3dcd5851,2022-03-31 20:12:23,24.171.248.77,9.122.217.42,Opera/9.14.(Windows NT 4.0; ayc-PE) Presto/2.9...,Insider Threat,Low,False,Require leg after school whom administration a...,Blocked
...,...,...,...,...,...,...,...,...,...,...
19992,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Ransomware,Critical,False,Forward something wife.,Recovered
19993,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Ransomware,Low,True,Fund method election possible.,Eradicated
19994,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Ransomware,Medium,False,Network minute act reflect.,Contained
19995,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Malware,Critical,False,Amount sit ten.,Contained
19996,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,Malware,High,True,Most structure several.,Contained

In [26]:
csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv" ,names = ["col1" , "col2" , "col3" , "col4" , "col5" , "col6" , "col7" , "col8" , "col9" , "col10"])
csv_2

,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10
0,Event ID,Timestamp,Source IP,Destination IP,User Agent,Attack Type,Attack Severity,Data Exfiltrated,Threat Intelligence,Response Action
1,2019969e-ecfa-41c4-b681-9b684bc3b3bf,2020-02-07 23:46:57,219.80.193.15,44.155.75.24,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv...,Ransomware,Critical,False,Crime low this behind option tax product.,Eradicated
2,1668e954-781f-4731-94dc-24218b983ba1,2021-05-25 19:03:44,110.155.68.245,178.123.150.38,Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KH...,Malware,Critical,True,Responsibility work way effect.,Eradicated
3,0ef24a20-1d25-41fa-81b8-e19fb63e9e4c,2022-01-04 09:08:07,171.153.115.83,76.187.142.133,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,Ransomware,High,False,Artist though type imagine food push.,Eradicated
4,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,DDoS,Critical,False,In still military despite TV look.,Contained
...,...,...,...,...,...,...,...,...,...,...
19996,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Ransomware,Critical,False,Forward something wife.,Recovered
19997,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Ransomware,Low,True,Fund method election possible.,Eradicated
19998,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Ransomware,Medium,False,Network minute act reflect.,Contained
19999,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Malware,Critical,False,Amount sit ten.,Contained
20000,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,Malware,High,True,Most structure several.,Contained

In [28]:
csv_2 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv")
csv_2

,Event ID,Timestamp,Source IP,Destination IP,User Agent,Attack Type,Attack Severity,Data Exfiltrated,Threat Intelligence,Response Action
0,2019969e-ecfa-41c4-b681-9b684bc3b3bf,2020-02-07 23:46:57,219.80.193.15,44.155.75.24,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv...,Ransomware,Critical,False,Crime low this behind option tax product.,Eradicated
1,1668e954-781f-4731-94dc-24218b983ba1,2021-05-25 19:03:44,110.155.68.245,178.123.150.38,Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KH...,Malware,Critical,True,Responsibility work way effect.,Eradicated
2,0ef24a20-1d25-41fa-81b8-e19fb63e9e4c,2022-01-04 09:08:07,171.153.115.83,76.187.142.133,Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) G...,Ransomware,High,False,Artist though type imagine food push.,Eradicated
3,073b6225-0998-488c-aa1c-23e49814b6ff,2022-10-12 19:48:43,29.49.228.195,89.39.7.177,Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit...,DDoS,Critical,False,In still military despite TV look.,Contained
4,783fd153-6b88-44c1-8db5-d882300088cc,2021-11-24 02:04:33,120.43.64.52,113.82.34.164,Mozilla/5.0 (iPad; CPU iPad OS 9_3_6 like Mac ...,Malware,Medium,False,Push always least police it range either.,Eradicated
...,...,...,...,...,...,...,...,...,...,...
19995,34e609d3-ce8e-49f3-a552-776496bd0eab,2022-10-26 15:11:16,50.182.104.127,71.205.220.209,Opera/9.90.(X11; Linux i686; kok-IN) Presto/2....,Ransomware,Critical,False,Forward something wife.,Recovered
19996,ab090f66-e2ba-4560-ab18-254e91bd042d,2022-07-20 08:59:24,68.76.164.160,174.127.187.150,Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like M...,Ransomware,Low,True,Fund method election possible.,Eradicated
19997,387ec9f5-e808-4753-84bb-deeaf679d592,2020-05-28 22:34:07,176.103.72.227,214.189.241.210,Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2...,Ransomware,Medium,False,Network minute act reflect.,Contained
19998,42106391-4666-4c50-9403-70af8084896f,2021-03-10 14:58:36,42.225.43.82,41.192.165.72,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,Malware,Critical,False,Amount sit ten.,Contained
19999,9d924511-534b-46db-bd62-dcb929a102bf,2020-08-06 04:28:58,62.221.185.243,109.185.82.70,Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171...,Malware,High,True,Most structure several.,Contained

In [ ]:
#csv_1 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv", header=None , names = ["col1" , "col2"])
#with open ("C:\\Users\\asus\\Documents\\pandas_unleashed\\ai_ml_cybersecurity_dataset.csv", r) as file:
#    for _in range(5):
#        print(file.readline())
 
#print(csv_1)
#print(csv_1)

                                                                                                                                                                                                                              col1  \
Event ID                             Timestamp           Source IP      Destination IP  User Agent                                         Attack Type Attack Severity Data Exfiltrated                        Threat Intelligence
2019969e-ecfa-41c4-b681-9b684bc3b3bf 2020-02-07 23:46:57 219.80.193.15  44.155.75.24    Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv:... Ransomware  Critical        False             Crime low this behind option tax product.
1668e954-781f-4731-94dc-24218b983ba1 2021-05-25 19:03:44 110.155.68.245 178.123.150.38  Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KHT... Malware     Critical        True                        Responsibility work way effect.
0ef24a20-1d25-41fa-81b8-e19fb63e9e4c 2022-01-04 09:08:07 171.153.115.83 76.187.142.133  Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) Ge... Ransomware  High            False                 Artist though type imagine food push.
073b6225-0998-488c-aa1c-23e49814b6ff 2022-10-12 19:48:43 29.49.228.195  89.39.7.177     Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit/... DDoS        Critical        False                    In still military despite TV look.
...                                                                                                                                                                                                                            ...
34e609d3-ce8e-49f3-a552-776496bd0eab 2022-10-26 15:11:16 50.182.104.127 71.205.220.209  Opera/9.90.(X11; Linux i686; kok-IN) Presto/2.9... Ransomware  Critical        False                               Forward something wife.
ab090f66-e2ba-4560-ab18-254e91bd042d 2022-07-20 08:59:24 68.76.164.160  174.127.187.150 Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like Ma... Ransomware  Low             True                         Fund method election possible.
387ec9f5-e808-4753-84bb-deeaf679d592 2020-05-28 22:34:07 176.103.72.227 214.189.241.210 Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2.... Ransomware  Medium          False                           Network minute act reflect.
42106391-4666-4c50-9403-70af8084896f 2021-03-10 14:58:36 42.225.43.82   41.192.165.72   Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5)... Malware     Critical        False                                       Amount sit ten.
9d924511-534b-46db-bd62-dcb929a102bf 2020-08-06 04:28:58 62.221.185.243 109.185.82.70   Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171 ... Malware     High            True                                Most structure several.

                                                                                                                                                                                                    col2
Event ID                             Timestamp           Source IP      Destination IP  User Agent                                         Attack Type Attack Severity Data Exfiltrated  Response Action
2019969e-ecfa-41c4-b681-9b684bc3b3bf 2020-02-07 23:46:57 219.80.193.15  44.155.75.24    Mozilla/5.0 (Macintosh; PPC Mac OS X 10_7_8 rv:... Ransomware  Critical        False                  Eradicated
1668e954-781f-4731-94dc-24218b983ba1 2021-05-25 19:03:44 110.155.68.245 178.123.150.38  Mozilla/5.0 (Windows 95) AppleWebKit/534.2 (KHT... Malware     Critical        True                   Eradicated
0ef24a20-1d25-41fa-81b8-e19fb63e9e4c 2022-01-04 09:08:07 171.153.115.83 76.187.142.133  Mozilla/5.0 (X11; Linux x86_64; rv:1.9.7.20) Ge... Ransomware  High            False                  Eradicated
073b6225-0998-488c-aa1c-23e49814b6ff 2022-10-12 19:48:43 29.49.228.195  89.39.7.177     Mozilla/5.0 (Linux; Android 7.1.1) AppleWebKit/... DDoS        Critical        False                   Contained
...                                                                                                                                                                                                  ...
34e609d3-ce8e-49f3-a552-776496bd0eab 2022-10-26 15:11:16 50.182.104.127 71.205.220.209  Opera/9.90.(X11; Linux i686; kok-IN) Presto/2.9... Ransomware  Critical        False                   Recovered
ab090f66-e2ba-4560-ab18-254e91bd042d 2022-07-20 08:59:24 68.76.164.160  174.127.187.150 Mozilla/5.0 (iPod; U; CPU iPhone OS 4_2 like Ma... Ransomware  Low             True                   Eradicated
387ec9f5-e808-4753-84bb-deeaf679d592 2020-05-28 22:34:07 176.103.72.227 214.189.241.210 Opera/9.60.(X11; Linux x86_64; yi-US) Presto/2.... Ransomware  Medium          False                   Contained
42106391-4666-4c50-9403-70af8084896f 2021-03-10 14:58:36 42.225.43.82   41.192.165.72   Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5)... Malware     Critical        False                   Contained
9d924511-534b-46db-bd62-dcb929a102bf 2020-08-06 04:28:58 62.221.185.243 109.185.82.70   Opera/8.76.(Windows 98; wae-CH) Presto/2.9.171 ... Malware     High            True                    Contained

[20001 rows x 2 columns]

In [47]:
import pandas as pd

csv_10 = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv" , dtype= {"ApplicantIncome" : "float"})

csv_10

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849.0,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583.0,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000.0,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583.0,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000.0,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900.0,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106.0,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072.0,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583.0,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583.0,0.0,133.0,360.0,0.0,Semiurban,N