#replace and interpolate

In [5]:
import pandas as pd

var = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv")
var.head(4)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y

In [24]:
#rep = var.replace(to_replace = "Male", value = "Female")
#rep = var.replace([1,2,3,4,5,6,7,8,9] , 22)
#rep =  var.replace("[A-Za-z#]", "yashraj" , regex = True)
rep =  var.replace( {"Loan_ID" : '[A-Za-z]' }, 22 , regex = True) 
rep.head(5)

C:\Users\asus\AppData\Local\Temp\ipykernel_11368\655771007.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  rep =  var.replace( {"Loan_ID" : '[A-Za-z]' }, 22 , regex = True)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,22,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,22,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,22,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,22,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,22,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [38]:
#frep = var.replace(1 , method = "bfill" , limit = 2)
fr = var.replace(1 , method = "bfill" , limit = 4 , inplace = True)
fr

C:\Users\asus\AppData\Local\Temp\ipykernel_11368\3616931856.py:2: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  fr = var.replace(1 , method = "bfill" , limit = 4 , inplace = True)

#interpolate

In [44]:
import pandas as pd

var = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv")
var.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,NaN,0,Graduate,Yes,3000,NaN,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,NaN,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [59]:
var = pd.read_csv("C:\\Users\\asus\\Documents\\pandas_unleashed\\loan.csv")
var.head(5)

inter = var.interpolate(method = "linear" , axis = 0)
inter.head(5)

C:\Users\asus\AppData\Local\Temp\ipykernel_11368\3071121975.py:4: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  inter = var.interpolate(method = "linear" , axis = 0)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,NaN,0,Graduate,Yes,3000,1933.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,103.5,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [67]:
#inter_dir = var.interpolate(limit_direction="both" , limit = 2)
inter_dir = var.interpolate(limit_direction="both" , limit = 2 , inplace = True)
#inter_dir = var.interpolate(limit_area = "inside")
inter_dir

C:\Users\asus\AppData\Local\Temp\ipykernel_11368\2219392991.py:2: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  inter_dir = var.interpolate(limit_direction="both" , limit = 2 , inplace = True)